# -*- coding: utf-8 -*-
"""test_f.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGwkutu2oXt-j7gKH7xMvFu4Bb1RVqi8
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile test_f.py
# import matplotlib.pyplot as plt
# import numpy as np
# 
# def graficar_parabola():
#     x = np.linspace(-10, 10, 100)
#     y = x**2
# 
#     plt.plot(x, y, color='blue', linewidth=2)
#     plt.title("¡Prueba de sistema exitosa! f(x) = x^2")
#     plt.grid(True)
#     plt.show()

